version: '3.8'
services:

  mongodb:
    image: mongo:6.0.2
    container_name: mongodb
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/bookdb --quiet

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: dev-mem
    command: start-dev
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"
